services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # Porta padrão do RabbitMQ
      - "15672:15672" # Porta do plugin de gerenciamento

  postgres:
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: matchmanager
    ports:
      - "5432:5432"